name: OGC Building Blocks postprocess
description: Generates documentation and output files for OGC building blocks
author: Alejandro Villar
inputs:
  register_file:
    description: JSON register file for output
    default: build/register.json
  items_dir:
    description: Root directory where building blocks (subdirectories with bblock.json) are located
    default: _sources
  generated_docs_path:
    description: Output directory for documentation
    default: build/generateddocs
  base_url:
    description: Base URL to use for asset linkage
    default: https://raw.githubusercontent.com/${{github.repository}}/${{github.ref_name}}
  fail_on_error:
    description: Whether to fail on errors
    default: 'false'
  annotated_path:
    description: Output path for annotated schemas
    default: build/annotated
  clean:
    description: Whether to delete all output files and directories before generating new ones
    default: 'true'

runs:
  using: docker
  image: docker://ghcr.io/opengeospatial/bblocks-postprocess
  args:
    - '--register-file'
    - ${{ inputs.register_file }}
    - '--items-dir'
    - ${{ inputs.items_dir }}
    - '--generated-docs'
    - ${{ inputs.generated_docs_path }}
    - '--base-url'
    - ${{ inputs.base_url }}
    - '--fail-on-error'
    - ${{ inputs.fail_on_error }}
    - '--annotated-path'
    - ${{ inputs.annotated_path }}
    - '--clean'
    - ${{ inputs.clean }}
