name: OGC Building Blocks full postprocess
description: Generates documentation and output files for OGC building blocks, including Slate templats
author: Alejandro Villar
inputs:
  register_file:
    description: JSON register file for output
    default: build/register.json
  items_dir:
    description: Root directory where building blocks (subdirectories with bblock.json) are located
    default: _sources
  generated_docs_path:
    description: Output directory for documentation
    default: build/generateddocs
  base_url:
    description: Base URL to use for asset linkage
    default: https://raw.githubusercontent.com/${{github.repository}}/${{github.ref_name}}
  fail_on_error:
    description: Whether to fail on errors
    default: 'false'
  annotated_path:
    description: Output path for annotated schemas
    default: build/annotated
  clean:
    description: Whether to delete all output files and directories before generating new ones
    default: 'true'

runs:
  using: composite
  steps:
    - name: Run OGC BBR postprocess
      uses: opengeospatial/bblocks-postprocess/postprocess@v1
      with:
        register_file: ${{ inputs.register_file }}
        items_dir: ${{ inputs.items_dir }}
        generated_docs_path: ${{ inputs.generated_docs_path }}
        base_url: ${{ inputs.base_url }}
        fail_on_error: ${{ inputs.fail_on_error }}
        annotated_path: ${{ inputs.annotated_path }}
        clean: ${{ inputs.clean }}
    - name: Generate Slate documentation
      run: |
        GENDOCS_PATH="$(realpath "${{ inputs.generated_docs_path }}")"
        SOURCE_PATH="${GENDOCS_PATH}/slate/"
        BUILD_PATH="${GENDOCS_PATH}/slate-build/"
        docker run --rm -v "${SOURCE_PATH}:/srv/slate/source" \
          -v "${BUILD_PATH}:/srv/slate/build" slatedocs/slate build
      shell: bash
