name: Test action
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: OGC BB postprocess
        uses: avillar/bblocks-postprocess/full@master