name: Validate and process Building Blocks
on:
  workflow_call:
    inputs:
      register_file:
        type: string
        description: JSON register file for output
        default: build/register.json
      items_dir:
        type: string
        description: Root directory where building blocks (subdirectories with bblock.json) are located
        default: _sources
      generated_docs_path:
        type: string
        description: Output directory for documentation
        default: build/generateddocs
      base_url:
        type: string
        description: Base URL to use for asset linkage
        default: >-
          ${{ github.event.repository.has_pages
            && format('https://{0}.github.io/{1}', github.repository_owner, github.event.repository.name)
            || format('https://raw.githubusercontent.com/{0}/{1}', github.repository, github.ref_name) }}
      fail_on_error:
        type: string
        description: Whether to fail on errors
        default: 'true'
      annotated_path:
        type: string
        description: Output path for annotated schemas
        default: build/annotated
      clean:
        type: string
        description: Whether to delete all output files and directories before generating new ones
        default: 'true'
      config_file:
        type: string
        description: Building blocks submodule config file
        default: 'bblocks-config.yaml'
      test_outputs_path:
        type: string
        description: Directory for test output resources
        default: build/tests
      github_base_url:
        type: string
        description: Base URL for linking to GitHub content
        default: https://github.com/${{github.repository}}/blob/${{github.ref_name}}/
      ref:
        type: string
        description: Repository ref for checkout
        default: ${{ github.ref_name }}
      skip-build:
        type: boolean
        description: Whether to skip the BB build part of the process
        default: false
      skip-pages:
        type: boolean
        description: Whether to skip the GH pages build part of the process
        default: false
      deploy_viewer:
        type: boolean
        description: Whether to use the new building blocks viewer
        default: true
      viewer_path:
        type: string
        description: Path where to deploy the viewer
        default: '.'
      viewer_show_imported:
        type: number
        description: |
          Level up to which the deployed building blocks viewer will show imported building 
          blocks as well as local ones. 0 means "only local", and a negative number means
          "all imports".
        default: 0
    secrets:
      sparql_username:
        description: SPARQL Graph Store Protocol user name for push authentication
        required: false
      sparql_password:
        description: SPARQL Graph Store Protocol password for push authentication
        required: false


permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: bblocks
  cancel-in-progress: true

jobs:
  validate-and-process:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ inputs.ref }}
      - name: Update submodules
        run: git submodule update --recursive --remote
      - name: OGC BB postprocess
        if: ${{ !inputs.skip-build }}
        uses: opengeospatial/bblocks-postprocess/full@v1
        with:
          register_file: ${{ inputs.register_file }}
          items_dir: ${{ inputs.items_dir }}
          generated_docs_path: ${{ inputs.generated_docs_path }}
          base_url: ${{ inputs.base_url }}
          fail_on_error: ${{ inputs.fail_on_error }}
          annotated_path: ${{ inputs.annotated_path }}
          clean: ${{ inputs.clean }}
          config_file: ${{ inputs.config_file }}
          test_outputs_path: ${{ inputs.test_outputs_path }}
          github_base_url: ${{ inputs.github_base_url }}
          deploy_viewer: ${{ inputs.deploy_viewer && 'true' || 'false' }}
          viewer_path: ${{ inputs.viewer_path }}
          sparql_username: ${{ secrets.sparql_username }}
          sparql_password: ${{ secrets.sparql_password }}
      - name: Fix permissions, compress large _visited_properties.tsv, git pull
        run: |
          sudo chown -R $UID:$(id -g) . 
          sudo find "${{ inputs.annotated_path }}" -size +10M -name _visited_properties.tsv \
            -exec gzip \{\} \;
          git pull
      - name: Add & Commit
        if: ${{ !endsWith(github.repository, '/bblock-template') && !inputs.skip-build }}
        uses: EndBug/add-and-commit@v9
        with:
          message: Building blocks postprocessing
      - name: Remove _visited_properties.tsv from pages
        run: |
          sudo find "${{ inputs.annotated_path }}" -name _visited_properties.tsv -delete
          sudo find "${{ inputs.annotated_path }}" -name _visited_properties.tsv.gz -delete
      - name: Deploy Building Blocks viewer
        if: ${{ inputs.deploy_viewer && github.event.repository.has_pages && !inputs.skip-pages }}
        run: |
          OLD_WD="$(pwd)"
          REGISTER_FILE="$(realpath "${{ inputs.register_file }}")"
          if [ -n "${{ inputs.viewer_path }}" ]; then
            mkdir -p "${{ inputs.viewer_path }}"
            cd "${{ inputs.viewer_path }}"
          fi
          
          # If viewer path is '.' or './', clear it.
          # Otherwise, remove any leading './'
          BASE_URL="${{ inputs.viewer_path }}"
          if [[ "${BASE_URL}" =~ ^\./?$ ]]; then
            BASE_URL=
          else
            BASE_URL=${BASE_URL#./}
          fi
          # Add trailing slash to BASE_URL if not empty
          if [[ "${BASE_URL}" =~ [^/]$ ]]; then
            BASE_URL="${BASE_URL}/"
          fi
          
          cat << EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <link rel="icon" href="https://ogcincubator.github.io/bblocks-viewer/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>OGC Location Building Blocks</title>
            <script src="/${{ github.event.repository.name }}/${BASE_URL}config.js"></script>
            <script type="module" crossorigin src="https://ogcincubator.github.io/bblocks-viewer/assets/index.js"></script>
            <link rel="stylesheet" href="https://ogcincubator.github.io/bblocks-viewer/assets/index.css">
          </head>
          <body>
            <div id="app"></div>
          </body>
          </html>
          EOF
          
          cat << EOF > config.js
          window.bblocksRegister = '${{ format('https://{0}.github.io/{1}/{2}', github.repository_owner, github.event.repository.name, inputs.register_file) }}';
          window.bblocksViewer = {
            title: $(jq '.name // "${{ github.event.repository.name }}"' < "$REGISTER_FILE"),
            showImported: ${{ inputs.viewer_show_imported }},
            baseUrl: '/${{ github.event.repository.name }}/${BASE_URL}',
          };
          EOF
          
          if [ -f GIT_INFO ]; then
            TEMPFILE="$(mktemp)"
            jq -s '.[0].tooling."bblocks-viewer" = .[1] | .[0]' "$REGISTER_FILE" GIT_INFO > "$TEMPFILE"
            mv "$TEMPFILE" "$REGISTER_FILE"
            rm -f "$TEMPFILE"
          fi
          
          cd "$OLD_WD"
          
          if [ ! -f "404.html" ]; then
            cp "${{ inputs.viewer_path }}/index.html" 404.html
          fi
      - name: Setup Pages
        if: ${{ github.event.repository.has_pages && !inputs.skip-pages }}
        uses: actions/configure-pages@v3
      - name: Upload artifacts
        if: ${{ github.event.repository.has_pages && !inputs.skip-pages }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GH Pages
        if: ${{ github.event.repository.has_pages && !inputs.skip-pages }}
        id: deployment
        uses: actions/deploy-pages@v2
