name: Validate and process Building Blocks
on:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-and-process:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --recursive --remote
      - name: OGC BB postprocess
        uses: opengeospatial/bblocks-postprocess/full@v1
        with:
          fail_on_error: 'true'
      - name: Add & Commit
        if: ${{ !endsWith(github.repository, '/bblock-template') }}
        uses: EndBug/add-and-commit@v9
        with:
          message: Building blocks postprocessing
      - name: Create GH Pages index
        if: ${{ github.event.repository.has_pages }}
        shell: python
        run: |
          import json
          
          with open('build/register.json') as f:
            bblocks = json.load(f)
          
          with open('index.html', 'w') as f:
            f.write('<!doctype html><html><head><meta charset="utf-8"/><title>')
            f.write('${{ github.repository }}')
            f.write(' - Building Blocks</title><style>.validation-failed::before{color:red;content:"❌ "}.validation-passed::before{color:green;content:"✅️ "}</style></head><body><h1>')
            f.write('${{ github.repository }}')
            f.write('</h1><ul>')
            for bblock in sorted(bblocks, key=lambda x: x['itemIdentifier']):
              link = bblock.get('documentation', {}).get('slate', {}).get('url')
              name = bblock['name']
              identifier = bblock['itemIdentifier']
              validation = 'passed' if bblock.get('validationPassed', True) else 'failed'
              if link:
                f.write(f'<li class="validation-{validation}"><a href="{link}"><tt>{identifier}</tt> - {name}</a></li>')
              else:
                f.write(f'<li class="validation-{validation}"><tt>{identifier}</tt> - {name}</li>')
            f.write('</ul></body></html>')
      - name: Setup Pages
        if: ${{ github.event.repository.has_pages }}
        uses: actions/configure-pages@v3
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GH Pages
        if: ${{ github.event.repository.has_pages }}
        id: deployment
        uses: actions/deploy-pages@v2
