name: Validate and process Building Blocks
on:
  workflow_call:
    inputs:
      register_file:
        type: string
        description: JSON register file for output
        default: build/register.json
      items_dir:
        type: string
        description: Root directory where building blocks (subdirectories with bblock.json) are located
        default: _sources
      generated_docs_path:
        type: string
        description: Output directory for documentation
        default: build/generateddocs
      base_url:
        type: string
        description: Base URL to use for asset linkage
        default: >-
          ${{ github.event.repository.has_pages
            && format('https://{0}.github.io/{1}', github.repository_owner, github.event.repository.name)
            || format('https://raw.githubusercontent.com/{0}/{1}', github.repository, github.ref_name) }}
      fail_on_error:
        type: string
        description: Whether to fail on errors
        default: 'true'
      annotated_path:
        type: string
        description: Output path for annotated schemas
        default: build/annotated
      clean:
        type: string
        description: Whether to delete all output files and directories before generating new ones
        default: 'true'
      config_file:
        type: string
        description: Building blocks submodule config file
        default: 'bblocks-config.yaml'
      test_outputs_path:
        type: string
        description: Directory for test output resources
        default: build/tests
      github_base_url:
        type: string
        description: Base URL for linking to GitHub content
        default: https://github.com/${{github.repository}}/blob/${{github.ref_name}}/
      ref:
        type: string
        description: Repository ref for checkout
        default: ${{ github.ref_name }}
      skip-build:
        type: boolean
        description: Whether to skip the BB build part of the process
        default: false
      skip-pages:
        type: boolean
        description: Whether to skip the GH pages build part of the process
        default: false
      deploy-viewer:
        type: boolean
        description: Whether to use the new building blocks viewer
        default: false


permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: bblocks
  cancel-in-progress: true

jobs:
  validate-and-process:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ inputs.ref }}
      - name: Update submodules
        run: git submodule update --recursive --remote
      - name: OGC BB postprocess
        if: ${{ !inputs.skip-build }}
        uses: opengeospatial/bblocks-postprocess/full@v1
        with:
          register_file: ${{ inputs.register_file }}
          items_dir: ${{ inputs.items_dir }}
          generated_docs_path: ${{ inputs.generated_docs_path }}
          base_url: ${{ inputs.base_url }}
          fail_on_error: ${{ inputs.fail_on_error }}
          annotated_path: ${{ inputs.annotated_path }}
          clean: ${{ inputs.clean }}
          config_file: ${{ inputs.config_file }}
          test_outputs_path: ${{ inputs.test_outputs_path }}
          github_base_url: ${{ inputs.github_base_url }}
      - name: Compress large _visited_properties.tsv
        run: |
          sudo find "${{ inputs.annotated_path }}" -size +10M -name _visited_properties.tsv \
            -exec gzip \{\} \;
      - name: Add & Commit
        if: ${{ !endsWith(github.repository, '/bblock-template') && !inputs.skip-build }}
        uses: EndBug/add-and-commit@v9
        with:
          message: Building blocks postprocessing
      - name: Remove _visited_properties.tsv from pages
        run: |
          sudo find "${{ inputs.annotated_path }}" -name _visited_properties.tsv -delete
          sudo find "${{ inputs.annotated_path }}" -name _visited_properties.tsv.gz -delete
      - name: Create GH Pages index
        if: ${{ !inputs.deploy-viewer && github.event.repository.has_pages && !inputs.skip-pages }}
        shell: python
        run: |
          import json
          
          with open('${{ inputs.register_file }}') as f:
            bblocks = json.load(f)
            if isinstance(bblocks, dict):
              bblocks = bblocks.get('bblocks', ())
          
          with open('index.html', 'w') as f:
            f.write('<!doctype html><html><head><meta charset="utf-8"/><title>')
            f.write('${{ github.repository }}')
            f.write(' - Building Blocks</title><style>.validation-failed::before{color:red;content:"❌ "}.validation-passed::before{color:green;content:"✅️ "}</style></head><body><h1>')
            f.write('${{ github.repository }}')
            f.write('</h1><ul>')
            for bblock in sorted(bblocks, key=lambda x: x['itemIdentifier']):
              link = bblock.get('documentation', {}).get('slate', {}).get('url')
              name = bblock['name']
              identifier = bblock['itemIdentifier']
              validation = 'passed' if bblock.get('validationPassed', True) else 'failed'
              if link:
                f.write(f'<li class="validation-{validation}"><a href="{link}"><tt>{identifier}</tt> - {name}</a></li>')
              else:
                f.write(f'<li class="validation-{validation}"><tt>{identifier}</tt> - {name}</li>')
            f.write('</ul><p style="margin-top:1em"><a href="${{ inputs.test_outputs_path }}/report.html">Validation report</a></p></body></html>')
      - name: Deploy Building Blocks viewer
        if: ${{ inputs.deploy-viewer && github.event.repository.has_pages && !inputs.skip-pages }}
        run: |
          wget -q -O - https://github.com/ogcincubator/bblocks-viewer/archive/refs/heads/dist.tar.gz | tar zx --strip-components=1
          sed -i -r 's,/@BASE_URL@/,/${{ github.event.repository.name }}/,g' index.html 404.html assets/*.js assets/*.css
          cat << EOF > config.js
          window.bblocksRegisters = ['${{ format('https://{0}.github.io/{1}/{2}', github.repository_owner, github.event.repository.name, inputs.register_file) }}'];
          EOF
      - name: Setup Pages
        if: ${{ github.event.repository.has_pages && !inputs.skip-pages }}
        uses: actions/configure-pages@v3
      - name: Upload artifacts
        if: ${{ github.event.repository.has_pages && !inputs.skip-pages }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GH Pages
        if: ${{ github.event.repository.has_pages && !inputs.skip-pages }}
        id: deployment
        uses: actions/deploy-pages@v2
